### ISSUE TITLE
Problem with the title of the page in French

### ISSUE THREAD

**Issue by GregMage** [XOOPS/xmf#26]
I use this:

`$xoopsTpl->assign('xoops_pagetitle', \Xmf\Metagen::generateSeoTitle($category->getVar('category_name') . '-' . $xoopsModule->name()));`

The result:

> cat%E3%A9gorie-2-xmarticle - XOOPS Site

We should have this:

>  catégorie-2-xmarticle - XOOPS Site

**Comment by geekwright** [comment]
?Thanks for finding and reporting this. The issue should be resolved now in the XoopsCore25 master. Please verify when you can.

**Comment by GregMage** [comment]
Great, everything works!

Thank you
