### ISSUE TITLE
Xmf composer.json should require PHP >= 5.4.8 or change Xmf\Highlighter script

### ISSUE THREAD

**Issue by zyspec** [XOOPS/xmf#34]
Xmf\Highlighter uses a change in the way `mb_substr()` works between PHP 5.4.8 and previous versions. Specifically, passing  `null` as the length of string to return will not return the remainder of the string in PHP versions \< 5.4.8.  The issue is that in versions prior to 5.4.8 PHP will treat the `null` as a zero (0) so doesn't return the string as the script expects.  The result is the remainder of the string to parse is _lost_.

The Xmf\Highlighter::splitOnTag() method code either needs to be changed to use the `mb_strlen()` to determine string length or composer.json should be changed to require a version that will return the string as expected.

The line of code effected is:
`$haystack = mb_substr($haystack, $p1 + $l1, null, $encoding);`

**Comment by geekwright** [comment]
Keeping PHP 5.3 as the minimum target, consistent XOOPS 2.5.9

Leave it to me to get bitten by a decade old bug ;) Sorry.

**Comment by zyspec** [comment]
Thanks Richard.
