### ISSUE TITLE
GenericHelper::addLog() incorrectly declared

### ISSUE THREAD

**Issue by geekwright** [XOOPS/xmf#40]
The docblock declares that the *$log* parameter to addLog($log) is type *string*, but it clearly handles non-scalar input. The type should be *mixed*.

It may also be preferable to use json_encode rather than serialize to handle the non-scalar input.

Originally reported in https://github.com/XOOPS/XoopsCore25/pull/565

**Comment by mambax7** [comment]
I've changed the declaration to mixed, and even changed serialize to json_encode(), but it did not resolve it. 

When I tested it originally, the error was coming from the second part of the line 110, i.e.

```php
 $this->configs[$name]
```

**Comment by geekwright** [comment]
Yes, I see that. I got distracted by the buggy declaration. Sorry. I'll have both fixed in a bit.

I have been rearranging Xmf to make it easier to support 2.5 and next gen from a consolidated source, so some of that may come along.
