### ISSUE TITLE
getConfig from Array

### ISSUE THREAD

**Issue by mambax7** [XOOPS/xmf#46]
When Preference is an array, then we're getting:

>  Array to string conversion in file /class/libraries/vendor/xoops/xmf/src/Xmf/Module/Helper/GenericHelper.php line 110

This should fix that:

```php
    public function getConfig($name = null, $default = null)
    {
            if ($this->configs === null) {
                $this->initConfig();
            }
            if (!$name) {
                $this->addLog('Getting all config');
                return $this->configs;
            }
            if (!isset($this->configs[$name])) {
                $this->addLog("ERROR :: CONFIG '{$name}' does not exist");
                return null;
            }
            if (is_array($this->configs[$name])) {
                $this->addLog("Getting config '{$name}' : " . serialize($this->configs[$name]));
                return $this->configs[$name][0];
            } else {
                $this->addLog("Getting config '{$name}' : " . $this->configs[$name]);
                return $this->configs[$name];
            }
            return null;
    }
```

**Comment by geekwright** [comment]
This should be covered with these sections:

https://github.com/XOOPS/xmf/blob/b81c794cdc2813ec94e4c7995866c1d17a376165/src/Module/Helper/GenericHelper.php#L90

https://github.com/XOOPS/xmf/blob/b81c794cdc2813ec94e4c7995866c1d17a376165/src/Module/Helper/AbstractHelper.php#L122

I just tagged a new release, so do a composer update in libraries to make sure you are using the latest
