### ISSUE TITLE
Enhancement: Add method to Tables class to get column names for a table

### ISSUE THREAD

**Issue by zyspec** [XOOPS/xmf#83]
There are instances where it would be useful to be able to check the dB table column names. I believe running an `alterColumn()` on a non-existent column will return `false` but there are other use cases where being able to get all of the dB columns could be useful.

Having a method something like `getColumnNames($table)` using a query something like:

```
SELECT 
    COLUMN_NAME 
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE 
    TABLE_NAME  = '$table'
```
This query is ANSI standard compliant so should work on most dBs. The method would return an array of column names or false if `$table` wasn't valid or not found.

**Comment by geekwright** [comment]
In a pinch, you can use something like this:
```PHP
$tables = new \Xmf\Database\Tables();
$tableName   = 'modules';
$tableExists = $tables->useTable($tableName);
if($tableExists) {
    $tableDetails=$tables->dumpTables();
    \Xmf\Debug::dump($tableDetails[$tableName]['columns']);
}
```
The Tables and Migrate classes are intended to implement a design developed with outside tools, so as such are pretty specific in what they provide. General table and/or structure browsing was intentionally not included.

With the schema support in Migrate, you don't really need much to convert what is in the database to a saved schema. 

The only two things that will require extra code will be renaming a table or a column -- those look exactly like a drop for old and an add for the new to the schema routines. 

Tables::useTable($table) can be used to test if an old table exists, signalling the need to use renameTable() before using synchronizeSchema(). 

Tables::getColumnAttributes() is a corresponding safe way to check if a column exists.

**Comment by zyspec** [comment]
Thanks - I have found a work around. At the time this was written I was approaching the problem a different way which could have used something like the proposed `getColumnNames()`. We can definitely live without it
