### ISSUE TITLE
Error with xhelp staff and xmf

### ISSUE THREAD

**Issue by cesagonchu** [XOOPS/xmf#94]
When I go to:
/modules/xhelp/admin/staff.php?op=manageStaff
I get this error:
Warning: strtoupper() expects parameter 1 to be string, array given in file /class/libraries/vendor/xoops/xmf/src/Request.php line 83
___
My config:
xhelp and Xoops 2.5.11 latest versions (in english)
PHP 7.4.9
MYSQL 5.7.33-0ubuntu0.16.04.1

**Comment by mambax7** [comment]
I was wrong about it - it was xHelp problem, which is now fixed.
