### ISSUE TITLE
YAML Inline: Unknown: trim() string deprecated 

### ISSUE THREAD

**Issue by mambax7** [XOOPS/xmf#96]
Because we use an old version of YAML in order to keep it compatible with PHP 5.3.9, we are getting a deprecated message on admin side in latest versions of PHP:
`Unknown: trim(): Passing null to parameter #1 ($string) of type string is deprecated in file /class/libraries/vendor/symfony/yaml/Inline.php line 49`

Can we add typecast in our version, so the error disappears? 

```php
$value = trim((string)$value);
```

See: https://github.com/XoopsModules25x/newbb/issues/137

**Comment by geekwright** [comment]
For core this was handled here: https://github.com/XOOPS/XoopsCore25/commit/b73697f8f0d79ed2e22cae9db5f0573ebcd12d15

Will bump requirements to more recent after 2.5.11 release
